
const userAgentPool = [
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36',
    'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 14_7_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36',
    'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15',
];

const userAgentPoolMob = [
    'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Mobile Safari/537.36',
    'Mozilla/5.0 (Linux; Android 8.0.0; SM-G955U Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Mobile Safari/537.36',
    'Mozilla/5.0 (Linux; Android 13; SM-G981B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Mobile Safari/537.36',
    'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Mobile Safari/537.36',
    'Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1',
];

const socksproxyList = [
    // usa
    { ip: '184.181.217.220', port:4145 },
    { ip: '184.178.172.3', port:4145 },
    { ip: '174.75.211.222', port:4145 },
    { ip: '192.111.130.2', port:4145 },
    { ip: '72.214.108.67', port:4145 },
    { ip: '206.220.175.2', port:4145 },

    { ip: '98.175.31.222', port:4145 },
    { ip: '192.252.216.81', port:4145 },
    { ip: '72.195.114.169', port:4145 },
    { ip: '104.200.152.30', port:4145 },
    { ip: '107.152.98.5', port:4145 },
    { ip: '216.68.128.121', port:4145 },
    { ip: '72.195.34.42', port:4145 },
    { ip: '184.181.217.206', port:4145 },
    { ip: '199.116.114.11', port:4145 },
    { ip: '184.170.245.148', port:4145 },
    { ip: '184.170.248.5', port:4145 },

    // japan
    { ip: '38.48.252.4', port:9553 },
    { ip: '38.48.252.16', port:9553 },
    { ip: '38.48.242.86', port:9553 },
    { ip: '38.48.251.91', port:9553 },
    { ip: '38.48.224.84', port:9553 },
];

const headers_des_chrome = { // post_list, gallog
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
    'Accept-Encoding': 'gzip, deflate, br, zstd',
    'Accept-Language': 'ko-KR,ko;q=0.9',
    'Cache-Control': 'max-age=0',
    'Connection': 'keep-alive',
    'Host': 'gall.dcinside.com',
    'Pragma': 'no-cache',
    'Referer': 'https://www.dcinside.com/',
    'Sec-Fetch-Dest': 'document',
    'Sec-Fetch-Mode': 'navigate',
    'Sec-Fetch-Site': 'same-site',
    'Sec-Fetch-User': '?1',
    'Upgrade-Insecure-Requests': '1',
    'User-Agent': '',
    'sec-ch-ua': '"Google Chrome";v="135", "Not-A.Brand";v="8", "Chromium";v="135"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': 'Windows',
};

const headers_mob_chrome_comment_api = { // 댓글 API
    'Accept': '*/*',
    'Accept-Encoding': 'gzip, deflate, br, zstd',
    'Accept-Language': 'ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7',
    'Connection': 'keep-alive',
    'Content-Length': '',
    'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
    'Host': 'm.dcinside.com',
    'Origin': 'https://m.dcinside.com',
    'Referer': '',
    'Sec-Fetch-Dest': 'empty',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Site': 'same-origin',
    'User-Agent': '',
    'X-CSRF-TOKEN': '',
    'X-Requested-With': 'XMLHttpRequest',
    'sec-ch-ua': '"Google Chrome";v="136", "Not-A.Brand";v="99", "Chromium";v="136"',
    'sec-ch-ua-mobile': '?1',
    'sec-ch-ua-platform': 'Android',
};

const headers_mob_chrome_gallog = { // 모바일 갤로그
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
    'Accept-Encoding': 'gzip, deflate, br, zstd',
    'Accept-Language': 'ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7',
    'Cache-Control': 'no-cache',
    'Connection': 'keep-alive',
    'Host': 'm.dcinside.com',
    'Pragma': 'no-cache',
    'Sec-Fetch-Dest': 'document',
    'Sec-Fetch-Mode': 'navigate',
    'Sec-Fetch-Site': 'none',
    'Sec-Fetch-User': '?1',
    'Upgrade-Insecure-Requests': '1',
    'User-Agent': '',
    'sec-ch-ua': '"Google Chrome";v="136", "Not-A.Brand";v="99", "Chromium";v="136"',
    'sec-ch-ua-mobile': '?1',
    'sec-ch-ua-platform': 'Android',
}

const headers_des_brave = { // post_list
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8',
    'Accept-Encoding': 'gzip, deflate, br, zstd',
    'Accept-Language': 'ko-KR,ko;q=0.7',
    'Connection': 'keep-alive',
    'Host': 'gall.dcinside.com',
    'Referer': 'https://www.dcinside.com/',
    'Sec-Fetch-Dest': 'document',
    'Sec-Fetch-Mode': 'navigate',
    'Sec-Fetch-Site': 'same-site',
    'Sec-Fetch-User': '?1',
    'Sec-GPC': '1',
    'Upgrade-Insecure-Requests': '1',
    'User-Agent': '',
    'sec-ch-ua': '"Chromium";v="136", "Brave";v="136", "Not.A/Brand";v="99"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': 'Windows',
};

const headers_mob_brave_comment_api = { // 댓글 API
    'Accept': '*/*',
    'Accept-Encoding': 'gzip, deflate, br, zstd',
    'Accept-Language': 'ko-KR,ko;q=0.7',
    'Connection': 'keep-alive',
    'Content-Length': '',
    'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
    'Host': 'm.dcinside.com',
    'Origin': 'https://m.dcinside.com',
    'Referer': '',
    'Sec-Fetch-Dest': 'empty',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Site': 'same-origin',
    'Sec-GPC': '1',
    'User-Agent': '',
    'X-CSRF-TOKEN': '072e54fa37fe6c91a8ec1a4ed7058fa8',
    'X-Requested-With': 'XMLHttpRequest',
    'sec-ch-ua': '"Chromium";v="136", "Brave";v="136", "Not.A/Brand";v="99"',
    'sec-ch-ua-mobile': '?1',
    'sec-ch-ua-platform': 'Android',
};

const headers_des_edge = { // post_list
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
    'Accept-Encoding': 'gzip, deflate, br, zstd',
    'Accept-Language': 'ko,en;q=0.9,en-US;q=0.8',
    'Connection': 'keep-alive',
    'Host': 'gall.dcinside.com',
    'Referer': 'https://www.dcinside.com/',
    'sec-ch-ua-platform': 'Windows',
    'Sec-Fetch-Dest': 'document',
    'Sec-Fetch-Mode': 'navigate',
    'Sec-Fetch-Site': 'same-site',
    'Sec-Fetch-User': '?1',
    'Upgrade-Insecure-Requests': '1',
    'User-Agent': '',
    'sec-ch-ua': '"Microsoft Edge";v="135", "Not-A.Brand";v="8", "Chromium";v="135"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': "Windows",
};

const headers_mob_edge_comment_api = { // 댓글 API
    'Accept': '*/*',
    'Accept-Encoding': 'gzip, deflate, br, zstd',
    'Accept-Language': 'ko,en;q=0.9,en-US;q=0.8',
    'Connection': 'keep-alive',
    'Content-Length': '',
    'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
    'Host': 'm.dcinside.com',
    'Origin': 'https://m.dcinside.com',
    'Referer': '',
    'Sec-Fetch-Dest': 'empty',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Site': 'same-origin',
    'User-Agent': '',
    'X-CSRF-TOKEN': '',
    'X-Requested-With': 'XMLHttpRequest',
    'sec-ch-ua': '"Microsoft Edge";v="135", "Not-A.Brand";v="8", "Chromium";v="135"',
    'sec-ch-ua-mobile': '?1',
    'sec-ch-ua-platform': 'Android',
};

module.exports = {
    headers_des_chrome,
    headers_mob_chrome_comment_api,
    headers_mob_chrome_gallog,
    headers_des_edge,
    headers_mob_edge_comment_api,
    userAgentPool,
    userAgentPoolMob,
    socksproxyList,
};